# Generated by Django 2.0 on 2018-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180301_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='descript', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='title', max_length=25),
        ),
    ]
